language: node_js
node_js:
- stable
env:
  global:
  - SSH_KEY="id_rsa"
  - GIT_NAME="msuret"
  - GIT_EMAIL="msuret@dhatim.com"
  - SOURCE_DIR="build/reports/api-doc"
  - DEPLOY_BRANCH="master"
  - BINTRAY_NAME="msuret"
  - secure: g9k7okCpEL47LvS0MEmFAP39JQBHBELfiXP8/d+eXv7PU+FaUj8OmFzoluhSKTrsiA6uMirO+YNfWI0X7AeSJdoYyhtgkvBAlk3QdGUNnnEbQ2L/xs7xXbSLkrxg0KxGKa58l6HRWQex0tCIm/LBOGkmOqlVAzHl3dOnh0EwYHXCMxhUNzX7FF5xS6akQzkU+cPIHK86u8cfnFKBAF5wcoW6EULNxpMqHrYv/BGt3uDdfPDbSs/Zyk3k/0ZEEDCloeDBvJmDSe1BIPt34vni48kGoVF4uPIQWgqIJFzQzSfgMJNl2msSppdx3YadyyGpCrIFw5T1v7RO+TAavkIR0eK9K9bRK0MFa8RqpmEZmWH4p//zZls6Fz6SzqCEbdP6bqVONxsKfjf1uTtuktmdXmbph2SBKX2b1Nkz4+tG9YF5IO0EQZCiUK2jNfx3hQqGXF4BRSL+TpJtO6IexLRdJ0cJCLcWfBnmbWRuhAFLyx+S3MXy/ok6UXApGkNEjVdCvcuedOgf+G0f9VmyRJUm7QeoTgcp04ATC3uXXxI3UlKp2C6eaxGmxptcTqzvwz+lChDwrtHfN3r7EU8yp3KJWFvCDoKYDuwYzOqp3Ah/hklfuAcG8e5GfKLPP8KZQu7f5OGeHK1SavPZc3T7DYD55Ykf0tvsmeui1zzDscBbocI=
branches:
  except:
  - gh-pages
after_success:
- npm run coveralls
- npm run api-doc
- openssl aes-256-cbc -K $encrypted_9fbbc0973790_key -iv $encrypted_9fbbc0973790_iv -in id_rsa.enc -out id_rsa -d
- npm run gh-pages
before_deploy:
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- git tag -f -a $TRAVIS_TAG -m $TRAVIS_TAG
- npm version from-git
deploy:
  provider: script
  script: npm run deploy-deb
  on:
    tags: true
after_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $SSH_KEY
- ssh-add $SSH_KEY
- git remote add deploy git@github.com:dhatim/cloudpass.git
- git push deploy
